
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pr_out = 3;
  public static final int id = 6;
  public static final int s_puntoComa = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int pr_system = 2;
  public static final int s_par_c = 8;
  public static final int s_par_a = 7;
  public static final int s_punto = 5;
  public static final int pr_println = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pr_system",
  "pr_out",
  "pr_println",
  "s_punto",
  "id",
  "s_par_a",
  "s_par_c",
  "s_puntoComa"
  };
}

